# Site settings
title: Heppler Research Notebook
description: "The open history notebook of historian Jason A. Heppler."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://notebook.jasonheppler.org" # the base hostname & protocol for your site

highlighter: pygments
gems: 
  - jekyll/scholar
  - jekyll-pandoc
repo: notebook

# We're using collections instead of posts
collections:
  note:
    output: true
  project:
    output: true

# Defaults      
defaults:
  - scope:
      path: ""
      type: note
    values:
      layout: note
      permalink: /:slug/
  - scope:
      path: ""
      type: project
    values:
      layout: project
      permalink: /project/:slug/

# Author information
author:
  name: Jason A. Heppler
  givenName: Jason
  familyName: Heppler
  avatar: me.jpg
  email: jason@jasonheppler.org
  twitter_username: jaheppler
  github_username:  hepplerj
  homeurl: http://jasonheppler.org

# Scholar settings
scholar:
  style: chicago-fullnote-bibliography
  source: ./_bibliography
  bibliography: bibliography.bib

# Build settings
source: source
destination: public
exclude: ["Rakefile", "README.md", "public"]
markdown: pandoc 
pandoc:
  extensions:
    - normalize
    - template: .pandoc/toc.html
    - toc
markdown_ext:  markdown,mkdown,mkdn,mkd,md,Rmd,rmd
exclude:
- Makefile
- Rakefile
- _drafts
- LICENSE
- README
- Gruntfile.js 
- package.json
- .jekyll-assets-cache
- .sass-cache
- .bundle