# Site settings
title: Open History Notebook
description: >
  The open history notebook of historian Jason A. Heppler.
baseurl: ""
url: "http://hepplerj.github.io"
highlighter: pygments
gems:
  - jekyll/scholar
  - jekyll-archives
permalink: /:title/
repo: notebook

# Jekyll settings
root: /
destination: public

scholar:
  style: chicago-fullnote-bibliography
  source: ./_bibliography
  bibliography: bibliography.bib

# Build settings
markdown: kramdown
# pandoc:
#   extensions:
#     - smart
exclude: ['jekyll-post.py', 'jekyll-post.tpl', 'jekyll_nbconvert.py', 'readings', 'Makefile', '_drafts']
include: ['readings.pdf']

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag

# Author information
author:
  name: Jason A. Heppler
  givenName: Jason
  familyName: Heppler
  avatar: me.jpg
  email: jason@jasonheppler.org
  twitter_username: jaheppler
  github_username:  hepplerj
  homeurl: http://jasonheppler.org
