# Site settings
title: Open History Notebook
description: "The open history notebook of historian Jason A. Heppler."
baseurl: ""
url: "http://notebook.jasonheppler.org"
root: /
highlighter: pygments
gems: ['jekyll/scholar']
permalink: /:title/
repo: notebook

source: source
destination: public
exclude: ["Rakefile", "README.md", "public"]

# Author information
author:
  name: Jason A. Heppler
  givenName: Jason
  familyName: Heppler
  avatar: me.jpg
  email: jason@jasonheppler.org
  twitter_username: jaheppler
  github_username:  hepplerj
  homeurl: http://jasonheppler.org

# Scholar settings
scholar:
  style: chicago-fullnote-bibliography
  source: ./_bibliography
  bibliography: bibliography.bib

# Build settings
destination: public
markdown: kramdown
# pandoc:
#   extensions:
#     - smart
markdown_ext:  markdown,mkdown,mkdn,mkd,md,Rmd,rmd
exclude: ['Makefile', 'Rakefile', '_drafts']
